### ISSUE TITLE
Unable to Create New Project

### ISSUE THREAD

**Issue by salvolpe** [aehrc/redmatch#25]
Hello! I am a graduate student researcher with Columbia University's Department of Biomedical Informatics and I am looking to integrate Redmatch as part of a larger clinical data interoperability pipeline. I have been deploying this through Docker on my local machine along with a HAPI FHIR server. However, I have been running into some issues when trying to create a new project in Redmatch.

Initially, I was running into this error that would pop-up immediately after logging in as well as when clicking 'Save': `Unable to create new project: TypeError: Cannot read property 'status' of undefined`
![image](https://user-images.githubusercontent.com/37944330/120843661-5f267e80-c53c-11eb-8608-fb5db072f451.png)

Due to the limitations of the implementation of the HAPI server I am working with, I had to try and switch Redmatch off 8080 to a different port, but I couldn't avoid getting this error. It also seemed to be consistently associated with a call to `localhost:8082/project` and I didn't see anywhere in the code a direct call to this port. The one spot I could find was in the React code referring to the environmental variable as defined in the Dockerfile, which did not mention 8082. I could not get it to work even being the only Docker container running.

I stepped away from this for a week or so, but then today when I went to run Redmatch alone again, I did not see the `undefined` error. However, today I did not have that error and instead ran into this 502 error: Unable to create new project: Error: Request failed with status code 502

![image](https://user-images.githubusercontent.com/37944330/120842246-72384f00-c53a-11eb-9869-8b3d992bf49b.png)

Would you be able to help me diagnose either of these issues (if the first were to come up again)? Thank you!

**Comment by ametke** [comment]
Hi Salvatore,

Not sure about the first one, but the second one is probably due to REDCap being in `localhost`. If you are running Redmatch in Docker, then `localhost` won't be your machine but rather the Docker container where Redmatch is running. Since there is no REDCap instance running there then that is probably the reason you are getting a 502. Hope this helps.

**Comment by salvolpe** [comment]
That was definitely helpful, thank you! It has now become an error 400 which is progress

![image](https://user-images.githubusercontent.com/37944330/120893329-bb42de80-c5e0-11eb-994d-4b681baa97c9.png)

**Comment by ametke** [comment]
Can you do a `docker logs redmatch` and try to find out what is happening in the back end?

**Comment by salvolpe** [comment]
When I ran the `docker logs` I found that the error was saying that the report ID was incorrect. I generated a new report and it worked that time, allowing me to progress into the projects screens. However, I have found the first source of the first port issue and wanted to know if seeing my `docker-compose.yml` file might help you see what the issue is:

```
version: "3"
volumes:
  mongodb_data_container:
    driver: local
  shared:
    driver: local
services:
  mongo:
    image: mongo:4.2.6-bionic
    container_name: mongo
    expose:
      - "27017"
    volumes:
      - mongodb_data_container:/data/db
  redmatch:
    image: aehrc/redmatch:1.2.1
    container_name: redmatch
    depends_on:
      - mongo
      - keycloak
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - redmatch.targetFolder=/usr/share/redmatch
      - redmatch.security.enabled=true
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:10001/auth/realms/Aehrc
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/auth/realms/Aehrc/protocol/openid-connect/certs
    ports:
      - 8090:8080
    volumes:
      - shared:/usr/share/redmatch
  redmatch-ui:
    image: aehrc/redmatch-ui:1.2.1
    container_name: redmatch-ui
    depends_on:
      - redmatch
    environment:
      - REACT_APP_REDMATCH_URL=http://localhost:8090
      - REACT_APP_TERMINOLOGY_URL=https://r4.ontoserver.csiro.au/fhir
    ports:
      - 8888:80
    volumes:
      - shared:/usr/share/redmatch
  keycloak:
    build: keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
      KEYCLOAK_IMPORT: tmp/realm-export.json
    ports:
      - 10001:8080
```

I am not very familiar with Docker and the appropriate way to change the ports, but I was trying to figure out how to switch it again. I changed the port number from 8080 to 8090 on the `ports` section under `services` (i.e. 8090:8080) and at the end of the REACT_APP_REDMATCH_URL. The `Cannot read property 'status' of undefined` error returned associated with the action `GET http://localhost:8080/project`

**Comment by ametke** [comment]
I have changed the way the UI is built and deployed in the most recent version so I suggest building from `master`. The docker compose file is now much simpler.

**Comment by salvolpe** [comment]
Hello. I pulled from the origin of `master` and now when I run `mvn clean verify -X` I get the following error:

```
INFO] Reactor Summary for Redmatch 1.3.0:
[INFO] 
[INFO] Redmatch ........................................... SUCCESS [  0.185 s]
[INFO] Redmatch UI ........................................ FAILURE [  2.221 s]
[INFO] Redmatch Server .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.632 s
[INFO] Finished at: 2021-06-15T18:32:58-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (exec-yarn-antlr4ts) on project ui: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (exec-yarn-antlr4ts) on project ui: Command execution failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:478)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:982)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:929)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:457)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :ui
```

So now I can't get into redmatch to handle any of the other issues

**Comment by ametke** [comment]
Hmm, not sure what could be the problem. Do you have `yarn` installed in your machine? Alternatively, I will release a new version soon and I will publish the Docker image so it should be easier for you to get it up and running.

**Comment by salvolpe** [comment]
I do have `yarn` installed on my machine I am using version 1.22.10. I will await that new version unless I can resolve the problem on my end before then, thank you for the notice. Hopefully the image will make it easier

**Comment by ametke** [comment]
I've published a new version of the Docker image [here](https://hub.docker.com/layers/155113895/aehrc/redmatch/1.3.0/images/sha256-55680cd73d9494e85eb741a894e11f280baad578f59657ff2a46eecfa67b2de3?context=explore). Give that one a try and let me know how it goes.

**Comment by salvolpe** [comment]
I'm not entirely sure how to do this correctly, but I pulled the image and ran it on my machine, but then had to assign it a port when I ran it, which I hadn't before. I chose 8080, but now when I go there I get brought here: https://auth.ontoserver.csiro.au/auth/realms/aehrc/protocol/openid-connect/auth?client_id=redmatch&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&state=bc28d5ab-ce49-4583-8eb8-591c4022f38c&response_mode=fragment&response_type=code&scope=openid&nonce=e0c5130c-e80b-410d-98fc-3b05f2ab5d6e

![image](https://user-images.githubusercontent.com/37944330/123047279-1f301a00-d3cb-11eb-8c39-57fde492e6dd.png)

**Comment by ametke** [comment]
Try putting the following Docker compose file in the top folder of the project (it use the Keycloak folder):

```
version: '3'
volumes:
  shared:
    driver: local
services:
  redmatch:
    image: aehrc/redmatch:1.3.0
    container_name: redmatch
    depends_on:
      - keycloak
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - 8080:8080
    volumes:
      - shared:/usr/share/redmatch
  keycloak:
      build: keycloak
      container_name: keycloak
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: secret
        KEYCLOAK_IMPORT: tmp/realm-export.json
      ports:
        - 10001:8080
        - 9990:9990
```

Then just do `docker-compose up -d`.
