### ISSUE TITLE
Server installation configuration?

### ISSUE THREAD

**Issue by rx2k** [aehrc/redmatch#33]
Hello,

i tried to install redmatch onto a virtual machine, so that multiple parties can access and try it out. In the end it even showed a loading screen which then redirected to localhost (on client PC) which obviously had no service (i think it was for keycloak) running. 
Is there a server configuration/version available? This would be very helpful, probably also for other people who can not install it on a local machine. Or is there an easy fix to suppress the redirection to local machine? Maybe just put in an option for an IP instead of the localhost reference?
Thanks in advance!

Cheers Raphael

**Comment by ametke** [comment]
Hi Raphael,

You need a Keycloak server to deal with auth. You can look at the one that is created by default when running the application locally to see how the client is set up. Here is a sample Docker compose file to configure Redmatch to talk to an external Keycloak (you just need to replace the Keycloak urls with the correct ones):

```
version: '3'
volumes:
  shared:
    driver: local
services:
  redmatch:
    image: aehrc/redmatch:1.3.4
    container_name: redmatch
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=https://yourserver.com/auth/realms/yourrealm
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://yourserver.com/auth/realms/yourrealm/protocol/openid-connect/certs
      - ui.keycloak.url=https://yourserver.com/auth/
      - ui.keycloak.realm=yourrealm
      - ui.keycloak.clientId=redmatch
    ports:
      - 80:8080
    volumes:
      - shared:/usr/share
```

Hope this helps.

Regards,

Alejandro
